services:
  ftp:
    image: stilliard/pure-ftpd:latest
    container_name: pure-ftpd
    restart: unless-stopped
    ports:
      - "21:21"  # FTP 控制連線 port
      - "30000-30009:30000-30009"  # FTP 被動模式 port 範圍
    environment:
      PUBLICHOST: "127.0.0.1"  # 改為你的主機實際 IP 或 localhost
      ADDED_FLAGS: "--tls=2"  # 強制 TLS 加密
    volumes:
      - ./ftpdata:/home/ftpusers                 # 使用者上傳資料
      - ./ftp/passwd:/etc/pure-ftpd/passwd       # 虛擬帳號資料庫
      - ./ftp/certs:/etc/ssl/private             # TLS 憑證
      - ./scripts:/scripts                       # 管理腳本
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "2345:80"  # 對外 http 服務，瀏覽器請用 http://localhost:2345/
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d  # nginx 虛擬主機設定檔
      - ./ftpdata:/var/www                # 掛載所有 user 的 web 目錄，對應 /var/www/user/web
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    image: dev-laravel
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./ftpdata:/var/www/html
    expose:
      - "9000"
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33060:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./scripts:/scripts
